stages:
  - pull_image
  - change_image_env
  - pull_dev

variables:
  GIT_CLEAN_FLAGS: none
# 1、找出那个镜像是最新的
# 2、将最新的镜像拉取到本地
pull_image:
  stage: pull_image
  before_script:
    - docker login -u admin -p Harbor12345 jianweisoft.cn
  script:
    - docker pull jianweisoft.cn/$FILE/$IMAGE_NAME:$IMAGE_TAG
  only:
    variables:
      - $IMAGE_NAME
      - $IMAGE_TAG
# 3、替换为最新的镜像，改变镜像的tag和name
change_image_env:
  tags:
    - scpe-devpre
  only:
    variables:
      - $IMAGE_NAME
      - $IMAGE_TAG
  stage: change_image_env
  variables:
    CUSTOM_IMAGE_NAME: ""
    CUSTOM_IMAGE_TAG: ""
  before_script:
    - pwd
    #  将.env中的$CUSTOM_IMAGE_NAME$CUSTOM_IMAGE_TAG替换为$IMAGE_NAME$IMAGE_TAG
    - sed -i "s/$CUSTOM_IMAGE_NAME=.*/$CUSTOM_IMAGE_NAME=jianweisoft.cn\/$FILE\/$IMAGE_NAME/g" ../resource/image.env
    - sed -i "s/$CUSTOM_IMAGE_TAG=.*/$CUSTOM_IMAGE_TAG=$IMAGE_TAG/g" ../resource/image.env
    - cat ../resource/image.env  > ./image.env
  script:
    - ./run_compose.sh
  artifacts:
    paths:
      - ./image.env
    expire_in: 1 week
