version: '3.7'
services:
  redis:
    image: redis:${REDIS_IMAGE_VERSION} # 你的redis版本
    restart: always
    container_name: ${REDIS_HOST}
    privileged: true
    ports:
      - ${REDIS_EXPOSED_PORT}:${REDIS_START_PORT}
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./redis/data-${ENV}:/usr/local/redis/data
      - ./redis/conf-${ENV}/redis.conf:/usr/local/redis/conf/redis.conf
      - ./redis/logs-${ENV}:/usr/local/redis/logs
    command: [ "redis-server", "/usr/local/redis/conf/redis.conf" ]
    networks:
      - intranet

  es:
    container_name: ${ES_HOST}
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_IMAGE_VERSION}
    restart: always
    env_file:
      - ${ACTUAL_ENV}
    volumes:
      - ./resources/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      xpack.security.enabled: "false" # discovery.type: "single-node"
      ES_JAVA_OPTS: -Xms256m -Xmx256m # -Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-s",
          "-f",
          "http://localhost:9200/_cat/health"
        ]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - ${ES_START_PORT}
    networks:
      - intranet # - 9300:9300

  fb:
    container_name: ${FB_HOST}
    entrypoint: "filebeat -e -strict.perms=false"
    image: docker.elastic.co/beats/filebeat:${FB_IMAGE_VERSION}
    restart: always
    env_file:
      - ${ACTUAL_ENV}
    depends_on:
      - es
    #        condition: service_healthy
    volumes:
      - ./resources/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/usr/share/filebeat/logs
    networks:
      - intranet

  kibana:
    container_name: ${KIBANA_HOST}
    image: docker.elastic.co/kibana/kibana:${KIBANA_IMAGE_VERSION}
    restart: always
    env_file:
      - ${ACTUAL_ENV}
   ## profiles: [ "dbvis" ]
    volumes:
      - ./resources/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    environment:
      ELASTICSEARCH_URL: http://${ES_HOST}:${ES_START_PORT}
    depends_on:
      - es
    #        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-s",
          "-f",
          "http://localhost:5601/api/status"
        ]
      interval: 3s
      timeout: 3s
      retries: 50
    ports:
      - ${KIBANA_EXPOSED_PORT}:${KIBANA_START_PORT}
    networks:
      - intranet

  comm-cron-ai:
    image: ${CRON_IMAGE_NAME}:${CRON_IMAGE_VERSION}
    container_name: ${CRON_HOST}
    restart: always
    ports:
      - ${CRON_START_HTTP_PORT}
      - ${CRON_START_GRPC_PORT}
    env_file:
      - ${ACTUAL_ENV}
    volumes:
      - ./resources/comm-cron:/data/conf
    networks:
      - intranet

  consul:
    image: hashicorp/consul:${CONSUL_IMAGE_VERSION}
    container_name: ${CONSUL_HOST}
    restart: always
    volumes:
      - ./consul/config-${ENV}:/consul/config
      - ./consul/data-${ENV}:/consul/data
      - ./consul/logs-${ENV}:/consul/logs
    command: consul agent -server -bootstrap-expect=1 -client=0.0.0.0 -ui -bind='{{ GetPrivateIP }}' -data-dir=/consul/data -node=consul-node -datacenter=dc1 -log-level=debug -enable-script-checks=true -config-dir=/consul/config
    ports:
      - ${CONSUL_HTTP_EXPOSED_PORT}:${CONSUL_HTTP_START_PORT}
      - ${CONSUL_HTTP2_START_PORT}/udp
    networks:
      - intranet

networks:
  intranet:
    driver: bridge
    name: ${DOCKER_NETWORK_NAME}

# build ui-js
#scp-ui $ docker build -t ui-js-i:1.0 .

# build appl-go
#scp-go $ docker build -t appl-go-i:1.0 .

# load image engine-cpp
#anywhere $ docker load -i <path to image tar file>, e.g., engine-cpp-i-20231208.tar.gz (Nextcloud, Onboarding_Files)


# build scp-int
#scp-int $ docker build -t scp-data:1.0 .

# build scp-inbound
#scp-inbound $ docker build -t scp-inbound:1.0 .

# start the full solution
#currentdir $ docker-compose --profile dev up -d
